finance/urls.py
from django.urls import include, path, re_path
# from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from django.conf import settings

admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('', include('returns.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

returns/urls.py
from django.urls import re_path

from . import views

app_name = 'returns'
urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^all_accounts/$', views.all_accounts, name='all_accounts'),
    re_path(r'^transaction/(?P<transaction_id>[0-9]+)/$', views.transaction, name='transaction'),
    re_path(r'^transaction/new/$', views.transaction_new, name='transaction_new'),
    re_path(r'^transaction/(?P<transaction_id>[0-9]+)/edit/$', views.transaction_edit, name='transaction_edit'),
    re_path(r'^account/(?P<account_id>[0-9]+)/$', views.account, name='account'),
    re_path(r'^account/new/$', views.account_new, name='account_new'),
    re_path(r'^account/(?P<account_id>[0-9]+)/edit$', views.account_edit, name='account_edit'),
    re_path(r'^account/(?P<account_id>[0-9]+)/refresh$', views.account_refresh, name='account_refresh'),
    re_path(r'^security/(?P<security_id>[0-9]+)/$', views.security, name='security'),
    re_path(r'^security/new/$', views.security_new, name='security_new'),
    re_path(r'^security/(?P<security_id>[0-9]+)/edit$', views.security_edit, name='security_edit'),
    re_path(r'^security/(?P<security_id>[0-9]+)/refresh$', views.security_refresh, name='security_refresh'),
    re_path(r'^timeperiod/$', views.timeperiod, name='timeperiod'),
    re_path(r'^add_interest/(?P<security_id>[0-9]+)$', views.add_interest, name='add_interest'),
    re_path(r'^add_mtm_data/$', views.add_mtm_data, name='add_mtm_data'),
    re_path(r'^update_hist_data/$', views.update_hist_data, name='update_hist_data'),
    re_path(r'^inflation/latest/$', views.inflation_latest, name='inflation_latest'),
    re_path(r'^inflation/new/$', views.inflation_new, name='inflation_new'),
    re_path(r'^inflation/(?P<inflation_id>[0-9]+)/$', views.inflation, name='inflation'),
    re_path(r'^inflation/(?P<inflation_id>[0-9]+)/edit$', views.inflation_edit, name='inflation_edit'),
]

returns/models.py
from time import mktime, sleep
from datetime import datetime, date, timedelta
from decimal import *
from moneyed import Money
from djmoney.models.fields import MoneyField, CurrencyField
from djmoney.forms.widgets import CURRENCY_CHOICES
from django_countries.fields import CountryField

from sys import stderr

from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.db import connection, models
from django.db.models import Sum, Subquery, OuterRef
from django.urls import reverse
from django.utils import timezone

from six import python_2_unicode_compatible
from alpha_vantage.timeseries import TimeSeries
# from pandas import DataFrame

from .calc import Solver
from .utilities import yearsago, last_day_of_month

from finance.settings import ALPHA_VANTAGE_KEY

import requests

class SecurityQuerySet(models.QuerySet):
    def securityOwnedBy(self,ownerID):
        pk_securities = Transaction.thobjects2.owner(ownerID) \
                                              .values_list('security', flat=True)
        return self.filter(pk__in=pk_securities)

    def markToMarket(self):
        return self.filter(mark_to_market=True)

    def kinds(self, kind):
        return self.filter(kind__in=kind)

    def active(self):
        return self.filter(active=True)

class SecurityManager(models.Manager):
    def get_queryset(self):
        return SecurityQuerySet(self.model, using=self._db)

    def securityOwnedBy(self,ownerID):
        return self.get_queryset().securityOwnedBy(ownerID)

    def markToMarket(self):
        return self.get_queryset().markToMarket()

    def kinds(self, kind):
        return self.get_queryset().kinds(kind)

    def active(self):
        return self.get_queryset().active()

    def saveCurrentMarkToMarketValue(self):
        # for each mark to market security get and save current value, random ordering
        markToMarketSecurities = self.get_queryset().markToMarket().active().order_by('?')[0:8]
        # today = timezone.now().date() + timezone.timedelta(days=-1)

        #ts = TimeSeries(key=ALPHA_VANTAGE_KEY, output_format='pandas')
        ts = TimeSeries(key=ALPHA_VANTAGE_KEY, output_format='csv')

        for s in markToMarketSecurities:
            try:
                value, date = s.markToMarket(ts)
                HistValuation.objects.update_or_create(
                        date = date,
                        security = s,
                        defaults = { 'value': value }
                )
            except:
                print("Error getting data for security ", s, file=stderr)

        return markToMarketSecurities

    def saveMultiCurrentMarkToMarketValue(self):
        # for each mark to market security get and save current value, random ordering
        markToMarketSecurities = self.get_queryset().markToMarket().active().order_by('?')[0:10]

        ts = TimeSeries(key=ALPHA_VANTAGE_KEY, output_format='csv')

        for s in markToMarketSecurities:
            # find which is the most recent entry
            try:
                latest_date = HistValuation.objects.security(s).latest('date').date
                if latest_date >= datetime.today().date():
                    # skip if already got data
                    print("Skip getting data for security ", s, file=stderr)
                    continue
            except:
                latest_date = (datetime.today() + timedelta(days=-30)).date()

            if s.symbol == '':
                # skip if no symbol
                print("Error (no symbol) getting data for security ", s, file=stderr)
                continue

            try:
                print("Get mark-to-market data for security ", s, file=stderr)
                valuation = s.markToMarketMultiple(ts, latest_date)
                for date, value in valuation:
                    HistValuation.objects.update_or_create(
                            date = date,
                            security = s,
                            defaults = { 'value': value }
                )
            except:
                print("Error getting data for security ", s, file=stderr)

        return markToMarketSecurities


@python_2_unicode_compatible
class Security(models.Model):
    # models a single security held in an account
    TAGESGELD = 'TG'
    AKTIE = 'AK'
    AKTIENETF = 'AF'
    BONDSETF = 'BF'
    BONDS = 'BD'
    ALTERSVORSORGE = 'AV'
    SEC_KIND_CHOICES = (
        (TAGESGELD,'Savings'),
        (AKTIE, 'Stock'),
        (AKTIENETF, 'Stock-ETF'),
        (BONDSETF, 'Bond-ETF'),
        (BONDS, 'Bond'),
        (ALTERSVORSORGE, 'Retirement'),
    )
    name = models.CharField('name of security',
                            max_length = 40)
    descrip = models.CharField('detailed description',
                               max_length = 400)
    url = models.URLField('URL for pricing info',
                          max_length = 400,
                          default = '',
                          blank = True)
    symbol = models.CharField('Security symbol for pricing lookup',
                              default = '',
                              max_length = 10,
                              blank = True)
    kind = models.CharField('kind of security',
                            max_length = 2,
                            choices = SEC_KIND_CHOICES,
                            default = AKTIENETF)
    mark_to_market = models.BooleanField('True if security priced to market',
                                         default = False)
    accumulate_interest = models.BooleanField('True if interest accumulates (e.g. savings accounts)',
                                              default = False)
    calc_interest =  models.DecimalField('Fixed interest rate (%)',
                                         max_digits = 6,
                                         decimal_places = 2,
                                         default = 0)
    currency = models.CharField('Currency',
                                max_length = 3,
                                choices = CURRENCY_CHOICES,
                                default = 'EUR')

    active = models.BooleanField('Active security',
                                 default=True)

    objects = SecurityManager()

    def __str__(self):
        return "%s (%s)" % (self.name, self.descrip)

    def get_absolute_url(self):
        return reverse('views.security', args=[str(self.id)])

    def getSymbol(self):
        return self.symbol

    def markToMarket(self, ts):
        if not self.mark_to_market:
            raise RuntimeError('Security not marked to market prices')

        if self.symbol == '':
            raise RuntimeError('No symbol for mark to market security')
        try:
            # query website using alpha vantage API
            counter = 0
            data_retrieved = False
            # if data was not retrieved, try again after short wait
            while (counter < 5 and not data_retrieved):
                try:
                    data, meta_data = ts.get_daily(self.symbol)
                    # skip first row
                    next(data)
                    # extract information
                    row = next(data)
                    #value = Decimal(float(data['4. close'][-1]))
                    value = Decimal(float(row[4]))
                    #date = datetime.strptime(str(data.index[-1]), "%Y-%m-%d %H:%M:%S").date()
                    date = datetime.strptime(str(row[0]), "%Y-%m-%d").date()
                    data_retrieved = True
                    sleep(12) # wait to not exceep API max
                except:
                    counter += 2
                    sleep(counter)
            price = Money(amount=value, currency=self.currency)
        except:
            raise RuntimeError('Trouble getting data for security', self.name)

        # screen scraping based on yahoo website
        # try:
        #     data = requests.get(self.url)
        #     value = Decimal(float(data.content))
        #     price = Money(amount=value,currency=self.currency)
        # except:
        #     raise RuntimeError('Trouble getting data for security', security.name)

        return price, date

    def markToMarketMultiple(self, ts, up_to_date):
        if not self.mark_to_market:
            raise RuntimeError('Security not marked to market prices')

        if self.symbol == '':
            raise RuntimeError('No symbol for mark to market security')
        try:
            # query website using alpha vantage API
            counter = 0
            data_retrieved = False
            # if data was not retrieved, try again after short wait
            valuation = []
            while (counter < 2 and not data_retrieved):
                try:
                    data, meta_data = ts.get_daily(self.symbol)
                    # skip first row
                    next(data)
                    # extract information
                    for row in data:
                        value = Decimal(float(row[4]))
                        date = datetime.strptime(str(row[0]), "%Y-%m-%d").date()
                        valuation.append([date, Money(amount=value, currency=self.currency)])
                        if date <= up_to_date:
                            break
                    data_retrieved = True
                    #sleep(12) # wait to not exceep API max
                except:
                    counter += 1
                    #sleep(counter)
        except:
            raise RuntimeError('Trouble getting data for security', self.name)
        return valuation


    def calcInterest(self, date, owner):
    # calculate interest for security based on for year leading up to date
        if not self.calc_interest > 0:
            raise RuntimeError('Security does not have fixed interest payment')
        total = SecurityValuation.objects.filter(security=self, date__lte=date, owner_id=owner).order_by('date').last().cur_value

returns/templates/returns/base-thistory.html
{% extends 'returns/base.html' %}

{% block preheader_block %}
{% if segPerf or chart_asset_history %}
{% load nvd3_tags %}
{% endif %}
{% endblock preheader_block%}

{% block header_block%}

{% load static %}

{% if segPerf or chart_asset_history %}
<link rel="stylesheet" type="text/css" href="{% static 'returns/css/nv.d3.min.css'%}"/>
<script type="text/javascript" src="{% static 'returns/js/d3.min.js'%} "></script>
<script type="text/javascript" src="{% static 'returns/js/nv.d3.min.js'%} "></script>

{% if segPerf %}

{% load_chart chart_asset_alloc.charttype chart_asset_alloc.chartdata chart_asset_alloc.chartcontainer chart_asset_alloc.extra %}
{% load_chart chart_asset_perf.charttype chart_asset_perf.chartdata chart_asset_perf.chartcontainer chart_asset_perf.extra %}

{% endif %}

{% if chart_asset_history %}

{% load_chart chart_asset_history.charttype chart_asset_history.chartdata chart_asset_history.chartcontainer chart_asset_history.extra %}

{% endif %}
{% endif %}

{% load djmoney %}

{% block add_header_block %}{% endblock add_header_block%}
{% endblock header_block%}

{% block body_block%}
{% block add_body_block%} {% endblock add_body_block%}

<h2>Financial performance</h2>
<p><strong>Return:</strong> {{ returns|floatformat:1 }}% (<a href="{% url 'returns:inflation_latest' %}">Inflation</a>: {{ inflation|floatformat:1 }}%)</p>

<p><strong>Total:</strong> {{ total }}
{% if cur_num %} (<strong>&#35;</strong> {{ cur_num }} ){% endif %}</p>

{% if segPerf %}
<h2><a href="#" onclick="toggle_visibility('seg-perf-div');">Segments performance</a></h2>
<div id="seg-perf-div" style="display:none">
<table class="table table-condensed" id="seg_perf">
<thead>
  <tr>
    <th></th>
    <th>YTD return</th>
    <th>Last year return</th>
    <th>Overall return</th>
    <th>Total value</th>
    <th>Of total</th>
  </tr>
</thead>
<tbody>
{% for key, items in segPerf.items %}
  <tr>
    <th class="row">{{ key }}</th>
    <td class="text-right">{{ items.rYTD|floatformat:1 }}%</td>
    <td class="text-right">{{ items.r1Y|floatformat:1 }}%</td>
    <td class="text-right">{{ items.rInfY|floatformat:1 }}%</td>
    <td class="text-right">{{ items.tYTD }}</td>
    <td class="text-right">{{ items.frac|floatformat:1 }}%</td>
  </tr>
{% endfor %}
</tbody>
</table>
</div>

{% include_container chart_asset_perf.chartcontainer 450 '100%' %}
{% include_container chart_asset_alloc.chartcontainer 450 450 %}
{% endif %}

{% if histPerf %}
<h2><a href="#" onclick="toggle_visibility('hist-perf-div');">Historical performance</a></h2>
<div id="hist-perf-div" style="display:block">
<table id="hist_perf" class="table table-condensed">
<thead>
  <tr>
    <th>Time span</th>
    <th>Initial value</th>
    <th>Annualized return</th>
    <th>Inflation</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td>YTD</td>
    <td class="text-right">{{ histPerf.iYTD }}</td>
    <td class="text-right">{{ histPerf.rYTD|floatformat:1 }}%</td>
    <td class="text-right">{{ histPerf.inYTD|floatformat:1 }}%</td>
  </tr>
  <tr>
    <td>Last year</td>
    <td class="text-right">{{ histPerf.i1Y }}</td>
    <td class="text-right">{{ histPerf.r1Y|floatformat:1 }}%</td>
    <td class="text-right">{{ histPerf.in1Y|floatformat:1 }}%</td>
  </tr>
  <tr>
    <td>Last 5 years</td>
    <td class="text-right">{{ histPerf.i5Y }}</td>
    <td class="text-right">{{ histPerf.r5Y|floatformat:1 }}%</td>
    <td class="text-right">{{ histPerf.in5Y|floatformat:1 }}%</td>
  </tr>
  <tr>
    <td>Overall</td>
    <td class="text-right">{{ histPerf.iInfY }}</td>
    <td class="text-right">{{ histPerf.rInfY|floatformat:1 }}%</td>
    <td class="text-right">{{ histPerf.inInfY|floatformat:1 }}%</td>
  </tr>
</tbody>
</table>
</div>
{% endif %}

{% if chart_asset_history %}
{% include_container chart_asset_history.chartcontainer 450 '100%' %}
{% endif %}

{% if transaction_list %}
<h2><a href="#" onclick="toggle_visibility('transactions-list-div');">Transaction history</a></h2>
{% include "returns/t-history.html" %}
{% endif %}
{% endblock body_block%}

returns/templates/returns/base.html
<!DOCTYPE html>
<html>
  {% block preheader_block%}{% endblock %}
  <head>
    <title>Investments -{% block title_block%} {% endblock %}</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'returns/apple-icon-57x57.png'  %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'returns/apple-icon-60x60.png'  %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'returns/apple-icon-72x72.png'  %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'returns/apple-icon-114x114.png'  %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'returns/apple-icon-120x120.png'  %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'returns/apple-icon-144x144.png'  %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'returns/apple-icon-152x152.png'  %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'returns/apple-icon-180x180.png'  %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'returns/android-icon-192x192.png'  %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'returns/favicon.ico' %}"/>
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'returns/favicon-32x32.png'  %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'returns/favicon-96x96.png'  %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'returns/favicon-16x16.png'  %}">
    <link rel="manifest" href="{% static 'returns/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'returns/ms-icon-144x144.png'  %}">
    <meta name="theme-color" content="#ffffff">

    <link rel="stylesheet" type="text/css" href="{% static 'returns/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'returns/css/bootstrap-theme.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'returns/css/returns.css' %}"/>
    <script type="text/javascript" src="{% static 'returns/js/jquery-2.2.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'returns/js/bootstrap.min.js' %}"></script>
    {% block header_block %}{% endblock %}

    <script language="javascript">
      function toggle_visibility(id) {
      var e = document.getElementById(id);
      if (e.style.display == "block")
      e.style.display = "none";
      else
      e.style.display = "block";
      }
    </script>
  </head>
 <body>
   <div class="container">
     <div class="page-header">
       <h1>Finance portal</h1>
     </div>
     <nav class="navbar navbar-default">
       <div class="container-fluid">
	 <!-- Brand and toggle get grouped for better mobile display -->
	 {% if user.is_authenticated %}
         <div class="navbar-header">
	   <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar-collapse" aria-expanded="false">
	     <span class="sr-only">Toggle navigation</span>
	     <span class="icon-bar"></span>
	     <span class="icon-bar"></span>
	     <span class="icon-bar"></span>
	   </button>
	   <a class="navbar-brand" href="{% url 'returns:index' %}">Home</a>
	 </div>

	 <!-- Collect the nav links, forms, and other content for toggling -->
	 <div class="collapse navbar-collapse" id="main-navbar-collapse">
	   <ul class="nav navbar-nav">
	     <li class="dropdown">
	       <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Add <span class="caret"></span></a>
	       <ul class="dropdown-menu">
		 <li><a href="{% url 'returns:transaction_new' %}">New Transaction</a></li>
		 <li><a href="{% url 'returns:security_new' %}">New Security</a></li>
		 <li><a href="{% url 'returns:account_new' %}">New Account</a></li>
		 <li role="separator" class="divider"></li>
		 <li><a href="{% url 'returns:inflation_new' %}">Inflation data</a></li>
		 <li role="separator" class="divider"></li>
		 <li><a href="{% url 'returns:update_hist_data' %}">Update valuations</a></li>
 		 <li><a href="{% url 'returns:add_mtm_data' %}">Market data</a></li>
	       </ul>
	     </li>
	     <li class="dropdown">
	       <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Analyse <span class="caret"></span></a>
	       <ul class="dropdown-menu">
		 <li><a href="{% url 'returns:all_accounts' %}">All</a></li>
		 <li><a href="{% url 'returns:timeperiod' %}">Restricted</a></li>
	       </ul>
	     </li>
	   </ul>
	   <ul class="nav navbar-nav navbar-right">
	     <li><a href="{% url 'logout' %}?next=/">Sign out</a></li>
	   </ul>
	 </div><!-- /.navbar-collapse -->
	 {% else %}
	 <div class="navbar-header">
	   <a class="navbar-brand" href="{% url 'login' %}">Sign in</a>
	 </div>
	 {% endif %}
       </div><!-- /.container-fluid -->
     </nav>
     {% block body_block%}{% endblock %}
     <div class="footer">
       <small>&#169; 2016-{% now "Y" %} - A. Wechsung</small>
     </div>
   </div>
 </body>
</html>

returns/templates/returns/security.html
{% extends 'returns/base-thistory.html' %}
{% block title_block %} {{ security.name }} (#{{ security.id }}){% endblock title_block %}
{% block add_body_block %}

<h1>Security {{ security.name }} &ensp; <a class="btn btn-default btn-sm" href="{% url 'returns:security_edit' security_id=security.id %}" role="button"><span class="glyphicon glyphicon-pencil"></span></a>
{% if security.accumulate_interest == True and security.calc_interest > 0.0 %}&ensp;<a class="btn btn-default btn-sm" href="{% url 'returns:add_interest' security_id=security.id %}" role="button"><span class="glyphicon glyphicon-signal"></span></a>
{% endif %}&ensp;<a class="btn btn-default btn-sm" href="{% url 'returns:security_refresh' security_id=security.id %}" role="button"><span class="glyphicon glyphicon-refresh"></span></a></h1> 

<p><strong>Security ID: </strong>{{ security.id }}
<br />
{{ security.descrip }}
</p>

{% if security.mark_to_market == True %}
<p>Priced at market value.</p>
{% endif %}

{% if security.accumulate_interest == True %}
<p>Accumulates interest.</p>
{% if security.calc_interest > 0.0 %}
<p>Fixed interest rate: {{ security.calc_interest }}%</p>
{% endif %}
{% endif %}

{% endblock add_body_block%}

returns/templates/returns/select2.html
{% extends 'returns/base-thistory.html' %}
{% block title_block %} Restricted timeperiod {% endblock title_block %}
{% block add_body_block %}
<h1>Restricted timeperiod</h1>

{% if beginDate %}
<h2>Time range</h2>
<p>{{ beginDate }} through {{ endDate }}</p>
{% endif %}

<a href="#" onclick="toggle_visibility('selected-div');">
{% if selected_kinds %}
<h2>Selected kinds of securities</h2>
{% elif selected_accounts %}
<h2>Selected accounts</h2>
{% elif selected_securities %}
<h2>Selected securities</h2>
{% endif %}
</a>

<div id="selected-div" style="display:none">
<table class="table table-condensed" id="selected_perf">
<thead>
  <tr>
    <th>Selection</th>
    <th>Details</th>
  </tr>
</thead>
<tbody>
    {% if selected_kinds or selected_securities %}
      {% for security in security_list %}
      <tr>
        <td>{{ security.name }} ({{ security.descrip }})</td>
	<td><a href="{% url 'returns:security' security.id %}"><span class="glyphicon glyphicon-info-sign"></span></a>&ensp;<a href="{% url 'returns:security_edit' security_id=security.id %}"><span class="glyphicon glyphicon-pencil"></span></a></td>
      </tr>
      {% endfor %}
    {% else %}
      {% for account in account_list %}
      <tr>
	<td scope="row">{{ account.name }}</a></td>
        <td><a href="{% url 'returns:account' account.id %}"><span class="glyphicon glyphicon-info-sign"></span></a>&ensp;<a href="{% url 'returns:account_edit' account_id=account.id %}"><span class="glyphicon glyphicon-pencil"></span></a></td>
      </tr>
      {% endfor %}
    {% endif %}
</tbody>
</table>
</div>
{% endblock add_body_block%}

returns/templates/returns/t-history.html
<div id="transactions-list-div" style="display:block">
  <table id="transaction-history" class="table table-condensed">
    <thead>
      <tr>
	<th>Date</th>
	<th>Kind</th>
	<th>Account</th>
	<th>Security</th>
	<th>Cashflow</th>
	<th></th>
      </tr>
    </thead>
    <tbody>
      {% for transaction in transaction_list %}
      <tr>
	<th scope="row"><a href="{% url 'returns:transaction' transaction.id %}">{{ transaction.date }}</a></th>
	<td>{{ transaction.get_kind_display|title }}</td>
	<td><a href="{% url 'returns:account' transaction.account_id %}">{{ transaction.account.name }}</a></td>
	<td><a href="{% url 'returns:security' transaction.security_id %}">{{ transaction.security.descrip }}</a></td>
	<td class="text-right">{{ transaction.cashflow }}</td>
	<td><a href="{% url 'returns:transaction_edit' transaction_id=transaction.id %}"><span class="glyphicon glyphicon-pencil"></span></a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

returns/templates/returns/transaction.html
{% extends 'returns/base.html' %}
{% block title_block %} Transaction #{{ transaction.id }}{% endblock title_block %}
{% block body_block %}
<h1>Transaction &ensp;<a class="btn
btn-default btn-sm" href="{% url 'returns:transaction_edit' transaction_id=transaction.id %}" role="button"><span class="glyphicon glyphicon-pencil"></span></a></h1>

<p><strong>Transaction ID: </strong>{{ transaction.id }}
<p><strong>Date: </strong>{{ transaction.date }}

<p><strong>Account: </strong><a href="{% url 'returns:account' transaction.account.id %}">{{ transaction.account.name }}</a>
<p><strong>Security: </strong><a href="{% url 'returns:security' transaction.security.id %}">{{ transaction.security.descrip }}</a> ({{ transaction.security.name }})</p>

<p>
{% if transaction.kind == "BU" %}
Buy{% if transaction.num_transacted > 0.0 %} {{ transaction.num_transacted|floatformat:3 }}{%endif %}:
{% endif %}
{% if transaction.kind == "SE" %}
Sell{% if transaction.num_transacted < 0.0 %} {{ transaction.num_transacted|floatformat:3 }}{%endif %}:
{% endif %}
{% if transaction.kind == "IN" %}
Interest payment:
{% endif %}
{% if transaction.kind == "DI" %}
Dividend payment:
{% endif %}
{% if transaction.kind == "WD" %}
Write down:
{% endif %}
{{ transaction.cashflow }}
</p>

{% if transaction.expenses > 0 %}
<p><strong>Expenses: </strong> {{ transaction.expenses }}</p>
{% endif %}
{% if transaction.tax > 0 %}
<p><strong>Tax: </strong> {{ transaction.tax }}</p>
{% endif %}

{% endblock body_block %}